/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eVoto.Interfaz;

import eVoto.cod.Votante;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ccepeda
 */
public class Listar extends java.awt.Frame {

    public ArrayList<Votante> listaVotantes;

    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }

    public Listar(ArrayList<Votante> lista) {
        
        
        initComponents();
        listaVotantes = lista;
        cargarDatosVotantes();
    }

    private void cargarDatosVotantes() {

        Object[] row;

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("CEDULA");
        model.addColumn("NOMBRES");
        model.addColumn("APELLIDOS");
        model.addColumn("GENERO");
        tblVotantes.setModel(model);

        if (listaVotantes != null && !listaVotantes.isEmpty()) {
            for (Votante votante : listaVotantes) {
                row = new Object[4];
                row[0] = votante.getCedula();
                row[1] = votante.getNombre();
                row[2] = votante.getApellido();
                row[3] = votante.getSexo();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVotantes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setText("LISTA VOTANTES REGISTRADOS");
        jPanel1.add(jLabel1);

        tblVotantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombres", "Apellido", "Genero"
            }
        ));
        jScrollPane1.setViewportView(tblVotantes);

        jPanel1.add(jScrollPane1);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Inadministrador inadministrador = new Inadministrador(listaVotantes);
        inadministrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVotantes;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Votante> getListaVotantes() {
        return listaVotantes;
    }

    public void setListaVotantes(ArrayList<Votante> listaVotantes) {
        this.listaVotantes = listaVotantes;
    }

}
